[tools]
# Tools
pnpm = "11.1.2"
"npm:prettier" = "latest"
"github:JohnnyMorganz/StyLua" = "latest"

# LSPs
"github:luals/lua-language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"

# Languages
go = "1.26.4"
node = "26.1.0"
usage = "latest"

[tool_alias]
pnpm = "npm:pnpm"
