# basics
copy_on_select      clipboard

# bell
enable_audio_bell   no

# font
font_family      Dank Mono Regular
bold_font        Dank Mono Bold
italic_font      Dank Mono Italic

font_size           16.0

# cursor
cursor_shape        beam

# theme
include             night-owl.conf
