# bell
enable_audio_bell   no

# font
font_family         Dank Mono
font_size           16.0

# cursor
cursor_shape        beam

color0 #011627
color1 #ef5350
color2 #22da6e
color3 #c5e478
color4 #82aaff
color5 #c792ea
color6 #21c7a8
color7 #ffffff
color8 #575656
color9 #ef5350
color10 #22da6e
color11 #ffeb95
color12 #82aaff
color13 #c792ea
color14 #7fdbca
color15 #ffffff
background #011627
foreground #d6deeb
selection-background #1b90dd
# selection-foreground
cursor #d6deeb
