# bell
enable_audio_bell   no

# font
font_family         Dank Mono
font_size           16.0

# cursor
cursor #d6deeb
cursor_shape        beam

# Color Scheme {{{

#: The foreground and background colors
background #011627
foreground #d6deeb

#: The foreground for text selected with the mouse. A value of none
#: means to leave the color unchanged.
selection_foreground #000000

#: The background for text selected with the mouse.
selection_background #fffacd

#: The 256 terminal colors. There are 8 basic colors, each color has a
#: dull and bright version, for the first 16 colors. You can set the
#: remaining 240 colors as color16 to color255.

#: black
color0 #011627
color8 #575656

#: red
color1 #ef5350
color9 #ef5350

#: green
color2 #22da6e
color10 #22da6e

#: yellow
color3 #c5e478
color11 #ffeb95

#: blue
color4 #82aaff
color12 #82aaff

#: magenta
color5 #c792ea
color13 #c792ea

#: cyan
color6 #21c7a8
color14 #7fdbca

#: white
color7 #ffffff
color15 #ffffff

#: }}}
